/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MahjongRouteImport } from './routes/mahjong'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const MahjongRoute = MahjongRouteImport.update({
  id: '/mahjong',
  path: '/mahjong',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ingredients': typeof IngredientsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mahjong': typeof MahjongRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ingredients': typeof IngredientsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mahjong': typeof MahjongRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ingredients': typeof IngredientsRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/mahjong': typeof MahjongRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/ingredients' | '/links' | '/login' | '/mahjong'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/ingredients' | '/links' | '/login' | '/mahjong'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ingredients'
    | '/links'
    | '/login'
    | '/mahjong'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IngredientsRoute: typeof IngredientsRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  MahjongRoute: typeof MahjongRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mahjong': {
      id: '/mahjong'
      path: '/mahjong'
      fullPath: '/mahjong'
      preLoaderRoute: typeof MahjongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IngredientsRoute: IngredientsRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  MahjongRoute: MahjongRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
